### ISSUE TITLE
Duda Práctica 7

### ISSUE THREAD

**Issue by JVP2021** [JVP2021/practica_dwec_gestor_presupuesto#2]
Hola @pedroprieto , 

Tengo dudas al llamar a "anayadirGastos", ya que inserto por el prompt las nuevas etiquetas y no se aplica bien, solo se suman a las anteriores sin respetar que esten repetidas o no.

function EditarHandle(){

    this.handleEvent = function(e){
       //Pedir datos al usuario
       let desc = prompt("Introduce la descripción nueva", this.gasto.descripcion);
       let val = prompt("Introduce el valor nuevo", this.gasto.valor);
       let fech = prompt("Introduce la fecha nueva", this.gasto.fecha);
       let etiq = prompt("Inroduce las etiquetas nuevas", this.gasto.etiquetas);

       val = parseFloat(val);
       etiq = etiq.split(',');

       this.gasto.etiquetas = [];

       this.gasto.actualizarDescripcion(desc);
       this.gasto.actualizarValor(val);
       this.gasto.actualizarFecha(fech);
       //this.gasto.anyadirEtiquetas(etiq);
       //this.gasto.anyadirEtiquetas(etiq);
       //this.gasto.etiquetas = etiq;
      this.gasto.anyadirEtiquetas(etiq);

       console.log(this.gasto.etiquetas);

       repintar();
    }
}

Foto:

![imagen](https://user-images.githubusercontent.com/79107261/140184706-5230b55d-7db1-4fa0-9b39-e865e85096a1.png)

![imagen](https://user-images.githubusercontent.com/79107261/140184774-3a33f4c2-2dee-457c-9f35-a9e6595a65ff.png)

No se si estoy metiendo algún dato mal. Por favor, echale un ojo a ver si tu ves el fallo.

Un saludo.

**Comment by pedroprieto** [comment]
Buenas,

El problema es que te crea una etiqueta con todo el texto junto.

Recuerda que `anyadirEtiquetas` no necesita un vector como parámetro, sino una lista de parámetros. Debes utilizar el operador "spread" para hacer la conversión.

Además, no resetees la lista de etiquetas con `this.gasto.etiquetas = []`.

Un saludo!

**Comment by JVP2021** [comment]
Buenas tardes,
Tenías razón con:

```
etiq = etiq.split(',');
this.gasto.anyadirEtiquetas(...etiq);
```

Ya funciona perfectamente.

Muchas gracias.
