### ISSUE TITLE
Duda al hacer DELETE en la API

### ISSUE THREAD

**Issue by JVP2021** [JVP2021/practica_dwec_gestor_presupuesto#3]
Hola @pedroprieto ,

Tengo una duda con la función que hace el DELETE en la API (BorrarAPIHandle). Entiendo que hasta que no haga la función que añade datos a la API en mi identificar de usuario no hay datos (.../jesusvalero). 

Estaba probando la función del delete y al borrar entiendo que no borra nada y aún así no me da ningún error y el status es 200. Debería funcionar así o estoy haciendo algo mal?

En caso de que el funcionamiento sea correcto, ¿Hay alguna manera de capturar que no se ha borrado nada?

![imagen](https://user-images.githubusercontent.com/79107261/146051999-fdc4f241-1506-4fa8-9e63-6248694af828.png)

Un saludo y gracias de antemano.

**Comment by pedroprieto** [comment]
Buenas,

La API es muy básica y devolvía código 200 siempre, aunque no existiera elemento a borrar.

La he actualizado y ahora da error si el elemento no existe.

Un saludo!

**Comment by JVP2021** [comment]
Buenas,

¡Muchas gracias Pedro!

Un saludo!
