### ISSUE TITLE
Duda función enviarAPIHandle()

### ISSUE THREAD

**Issue by JVP2021** [JVP2021/practica_dwec_gestor_presupuesto#4]
Hola @pedroprieto ,

Tengo una duda con esa función, porque la de borrar y actualizar las pides con handleevent y la de enviar como función normal. ¿Es un error o es así?

![imagen](https://user-images.githubusercontent.com/79107261/146420514-de614741-ada6-4aed-8f02-94acf544cfbd.png)

Un saludo y gracias de antemano.

**Comment by pedroprieto** [comment]
Buenas,

En principio es así: la función de envío solo necesita los datos del formulario de envío (hay uno en toda la página). Por tanto, con una función te vale.

Las funciones de edición y borrado necesitan saber qué gasto es el que hay que borrar (hay varios en la página). Por tanto, tienes que tener alguna manera de pasar esa información al manejador. Con un objeto lo puedes hacer fácil.

De todos modos, ¿has visto otra posibilidad?

Un saludo!

**Comment by JVP2021** [comment]
Buenas,

Muchas gracias por la explicación, tienes razón. Yo esa función la había hecho con un handleEvent como las otras 2, pero tiene más sentido que sea una función "normal".

Vale, con los cambios terminados creo que la práctica hace todo lo que debe hacer en la API (cargar, enviar, modificar y borrar). ¿Puedes echarle, Pedro, un vistazo rápido para cercionarme de que no me dejo nada?

Mi usuario en la API: https://suhhtqjccd.execute-api.eu-west-1.amazonaws.com/latest/jesusvalero

Un saludo y muchas gracias de antemano.

**Comment by pedroprieto** [comment]
Muy buenas,

Parece que está todo correcto. Buen trabajo!!
